### PR TITLE
Add terrasteel AIOT, Update Gradle and fix depenedency issue

### LINKED ISSUE #42: Renam CommonProxy to ServerProxy
As the class called CommonProxy is only used on the server it either be renamed to `ServerProxy` or `ClientProxy` should extends it. A **Common**Proxy as the name says is usually instantiated on both sides not just on the server. This is very minor but it might confuse new developers.

### PR DESCRIPTION
**Pull request by noeppi-noeppi**
This PR adds a terrasteel AIOT. The recipes for this can be disabled in the config.
I also updated gradle to 5.6.1 and changed the curios version from `3.0-beta2` to `3.0` because botania needs at least `3.0` (Seriously how did you manage to start mc via `runClient` before if not all dependencies were available?). This also fixes #42 because CommonProxy is now a superclass of ClientProxy.

### CODE REVIEW

File: src/main/java/de/melanx/aiotbotania/items/terrasteel/ItemTerraSteelAIOT.java [hunk 1]
```diff
@@ -0,0 +1,480 @@
...
+        if (!player.world.isRemote && raycast.getType() == RayTraceResult.Type.BLOCK) {
+            Direction face = raycast.getFace();
+            if (AXE_MATERIALS.contains(player.getEntityWorld().getBlockState(raycast.getPos()).getMaterial())) {
+                this.breakOtherBlockAxe(player, stack, pos, pos, face);
+            } else {
+                this.breakOtherBlock(player, stack, pos, pos, face);
+            }
+            BotaniaAPI.instance().breakOnAllCursors(player, stack, pos, face);
+        }
+
```
Comment (MelanX) [inline src/main/java/de/melanx/aiotbotania/items/terrasteel/ItemTerraSteelAIOT.java:106]: empty line can be removed

File: src/main/java/de/melanx/aiotbotania/items/terrasteel/ItemTerraSteelAIOT.java [hunk 2]
```diff
@@ -0,0 +1,480 @@
...
+                setMana(stack, mana);
+                list.add(stack);
+            }
+
+            ItemStack stack = new ItemStack(this);
+            setMana(stack, CREATIVE_MANA[1]);
+            setTipped(stack);
+            list.add(stack);
+        }
+
```
Comment (MelanX) [inline src/main/java/de/melanx/aiotbotania/items/terrasteel/ItemTerraSteelAIOT.java:175]: empty line can be removed

File: src/main/java/de/melanx/aiotbotania/items/terrasteel/ItemTerraSteelAIOT.java [hunk 3]
```diff
@@ -0,0 +1,480 @@
...
+    public static int getLevel(ItemStack stack) {
+        int mana = getMana_(stack);
+
+        for (int i = LEVELS.length - 1; i > 0; --i) {
+            if (mana >= LEVELS[i]) {
+                return i;
+            }
+        }
+
```
Comment (MelanX) [inline src/main/java/de/melanx/aiotbotania/items/terrasteel/ItemTerraSteelAIOT.java:221]: empty line can be removed

File: src/main/java/de/melanx/aiotbotania/items/terrasteel/ItemTerraSteelAIOT.java [hunk 4]
```diff
@@ -0,0 +1,480 @@
...
+                    int range = level - 1;
+                    int rangeY = Math.max(1, range);
+                    if (range != 0 || level == 1) {
+                        Vector3i beginDiff = new Vector3i(doX ? -range : 0, doY ? -1 : 0, doZ ? -range : 0);
+                        Vector3i endDiff = new Vector3i(doX ? range : 0, doY ? rangeY * 2 - 1 : 0, doZ ? range : 0);
+                        ToolCommons.removeBlocksInIteration(player, stack, world, pos, beginDiff, endDiff, (state) -> MATERIALS.contains(state.getMaterial()), isTipped(stack));
+                        if (origLevel == 5) {
+                            PlayerHelper.grantCriterion((ServerPlayerEntity) player, ResourceLocationHelper.prefix("challenge/rank_ss_pick"), "code_triggered");
+                        }
+
```
Comment (MelanX) [inline src/main/java/de/melanx/aiotbotania/items/terrasteel/ItemTerraSteelAIOT.java:310]: empty line can be removed

File: src/main/java/de/melanx/aiotbotania/items/terrasteel/ItemTerraSteelAIOT.java [hunk 5]
```diff
@@ -0,0 +1,480 @@
...
+    private void onTickEnd(TickEvent.WorldTickEvent event) {
+        if (!event.world.isRemote) {
+            if (event.phase == TickEvent.Phase.END) {
+                RegistryKey<World> dim = event.world.func_234923_W_();
+                if (blockSwappers.containsKey(dim)) {
+                    Set<BlockSwapper> swappers = blockSwappers.get(dim);
+                    swappers.removeIf((next) -> next == null || !next.tick());
+                }
+            }
+
```
Comment (MelanX) [inline src/main/java/de/melanx/aiotbotania/items/terrasteel/ItemTerraSteelAIOT.java:332]: empty line can be removed

File: src/main/java/de/melanx/aiotbotania/items/terrasteel/ItemTerraSteelAIOT.java [hunk 6]
```diff
@@ -0,0 +1,480 @@
...
+                                isWood = BlockTags.LOGS.contains(block);
+                                isLeaf = BlockTags.LEAVES.contains(block);
+                            } while (!isWood && !isLeaf);
+
+                            int newRange = this.treatLeavesSpecial && isLeaf ? Math.min(3, cand.range - 1) : cand.range - 1;
+                            this.candidateQueue.offer(new BlockSwapper.SwapCandidate(adj, newRange));
+                        }
+                    }
+                }
+
```
Comment (MelanX) [inline src/main/java/de/melanx/aiotbotania/items/terrasteel/ItemTerraSteelAIOT.java:397]: empty line can be removed

File: src/main/java/de/melanx/aiotbotania/items/terrasteel/ItemTerraSteelAIOT.java [hunk 7]
```diff
@@ -0,0 +1,480 @@
...
+            for (int dx = -1; dx <= 1; ++dx) {
+                for (int dy = -1; dy <= 1; ++dy) {
+                    for (int dz = -1; dz <= 1; ++dz) {
+                        if (dx != 0 || dy != 0 || dz != 0) {
+                            coords.add(original.add(dx, dy, dz));
+                        }
+                    }
+                }
+            }
+
```
Comment (MelanX) [inline src/main/java/de/melanx/aiotbotania/items/terrasteel/ItemTerraSteelAIOT.java:414]: empty line can be removed

File: src/main/java/de/melanx/aiotbotania/items/terrasteel/ItemTerraSteelAIOT.java [hunk 8]
```diff
@@ -0,0 +1,480 @@
...
+            return 1f;
+        } else {
+            return (getMana(stack) - LEVELS[level]) / (float) LEVELS[level + 1];
+        }
+    }
+
+    @Nonnull
+    @Override
+    public ActionResultType onItemUse(@Nonnull ItemUseContext ctx) {
+
```
Comment (MelanX) [inline src/main/java/de/melanx/aiotbotania/items/terrasteel/ItemTerraSteelAIOT.java:472]: empty line can be removed

File: src/main/java/de/melanx/aiotbotania/items/terrasteel/ItemTerraSteelAIOT.java [hunk 9]
```diff
@@ -0,0 +1,480 @@
...
+        if (ItemNBTHelper.getBoolean(ctx.getItem(), "hoemode", true)) {
+            // Terra AIOT has not hoe mode as there's no terra hoe and right click toggles AOE mining
```
Comment (MelanX) [inline src/main/java/de/melanx/aiotbotania/items/terrasteel/ItemTerraSteelAIOT.java:474]: Hoe mode should be present.
For elementium and manasteel there is a hoe being added as well. Should be added for terrasteel, too. Maybe just tilt in 3x3 or 5x5 area. Shovel, too.

File: src/main/java/de/melanx/aiotbotania/items/terrasteel/RecipeTerraSteelAIOT.java [hunk 10]
```diff
@@ -0,0 +1,74 @@
...
+                } else if (INGREDIENT_AXE.test(stack) && !foundAxe) {
+                    foundAxe = true;
+                } else if (INGREDIENT_PICK.test(stack) && !foundPick) {
+                    foundPick = true;
+                } else {
+                    return false;
+                }
+            }
+        }
+
```
Comment (MelanX) [inline src/main/java/de/melanx/aiotbotania/items/terrasteel/RecipeTerraSteelAIOT.java:53]: empty line can be removed

File: src/main/java/de/melanx/aiotbotania/items/terrasteel/RecipeTerraSteelAIOT.java [hunk 11]
```diff
@@ -0,0 +1,74 @@
...
+    public ItemStack getCraftingResult(CraftingInventory inv) {
+        ItemStack stack = new ItemStack(Registration.terrasteel_aiot.get());
+
+        for(int j = 0; j < inv.getSizeInventory(); ++j) {
+            ItemStack ingredient = inv.getStackInSlot(j);
+            if (!ingredient.isEmpty() && INGREDIENT_PICK.test(ingredient)) {
+                stack.setTag(ingredient.getOrCreateTag().copy());
+            }
+        }
+
```
Comment (MelanX) [inline src/main/java/de/melanx/aiotbotania/items/terrasteel/RecipeTerraSteelAIOT.java:67]: i stop here pasting "empty line can be removed"

File: src/main/resources/assets/aiotbotania/lang/en_us.json [hunk 12]
```diff
@@ -27,6 +27,8 @@
   "item.aiotbotania.elementium_hoe": "Elementium Hoe",
   "item.aiotbotania.elementium_aiot": "Elementium AIOT",
 
+  "item.aiotbotania.terra_aiot": "Terrasteel AIOT",
+
```
Comment (MelanX) [inline src/main/resources/assets/aiotbotania/lang/en_us.json:31]: lexica botania entry is missing

File: src/main/java/de/melanx/aiotbotania/core/Registration.java [hunk 13]
```diff
@@ -2,6 +2,7 @@
 
 import de.melanx.aiotbotania.AIOTBotania;
 import de.melanx.aiotbotania.blocks.BlockCustomFarmland;
+import de.melanx.aiotbotania.core.config.ConfigHandler;
```
Comment (MelanX) [inline src/main/java/de/melanx/aiotbotania/core/Registration.java:5]: Unused import

File: src/main/java/de/melanx/aiotbotania/core/config/ConfigHandler.java [hunk 14]
```diff
@@ -15,11 +15,26 @@ public Client(ForgeConfigSpec.Builder builder) {
         }
     }
 
+    public static class Common {
+        public final BooleanValue TERRA_AIOT;
+
+        public Common(ForgeConfigSpec.Builder builder) {
+            TERRA_AIOT = builder.comment("If set to false, the recipes for the Terrasteel AIOT will be disabled. [default: true]")
+                    .define("terra_aiot.enabled", true);
```
Comment (MelanX) [inline src/main/java/de/melanx/aiotbotania/core/config/ConfigHandler.java:23]: should be named "terra_tier.enabled" (because of reasons below)

File: src/main/resources/assets/aiotbotania/lang/en_us.json (hunk 12 above)
Comment (noeppi-noeppi) [reply src/main/resources/assets/aiotbotania/lang/en_us.json:33]: I did not get this work. I dont know what I'm doing wrong but it just does not work.
